### ISSUE TITLE
Ability to show a tag without the delete button

### ISSUE THREAD

**Issue by markrickert** [ali312/TLTagsControl#1]
Hey there! Great control! I love it and plan on using it in a project, but I'd really like the ability to globally turn off the delete button on all tags (for when i'm displaying a list of tags instead of adding/editing tags)

Thanks again!

**Comment by ali312** [comment]
Hello
Thank you for your feedback

I'm going to add some customization to the control and will include the feature you've requested in the nearest update

**Comment by ali312** [comment]
Hello again @markrickert 
I've pushed my latest changes, which include the feature you've requested, feel free to use it :)
I guess the issue can be closed at this point
