### ISSUE TITLE
A spelling mistake in property

### ISSUE THREAD

**Issue by xnth97** [ali312/TLTagsControl#3]
@property (nonatomic, strong) UIColor *tagsBackgroungColor;

->

@property (nonatomic, strong) UIColor *tagsBackgroundColor;

:P

**Comment by AntonKuznetsov** [comment]
Hello @xnth97 and thank you for pointing out my mistake :)
I've seen your pull request. I'll check it tomorrow and merge it if everything is ok.

**Comment by ali312** [comment]
Hello @xnth97 and thank you for pointing out my mistake :)
I've seen your pull request. I'll check it tomorrow and merge it if everything is ok.

**Comment by xnth97** [comment]
@ali312 Thanks for reply and your great work! I do like your code and it's my pleasure to have the chance to contribute to it.
And sorry that I made a mistake in Sample (Line 84, ViewController.m). I didn't notice that all the tags of TagsControls point to one single NSMutableArray so it may crash if you tap on tags after editing others. Please fix NSLog(@"%@ tapped", _redListingTagControl.tags[index]) into NSLog(@"Tag %ld tapped", index) if it's ok.

**Comment by xnth97** [comment]
@ali312 Thanks for reply and your great work! I do like your code and it's my pleasure to have the chance to contribute to it.
And sorry that I made a mistake in Sample (Line 84, ViewController.m). I didn't notice that all the tags of TagsControls point to one single NSMutableArray so it may crash if you tap on tags after editing others. Also one single NSMutableArray may cause other crashes while editing tags (for instance, first delete the last tag of _defauldEditingTagControl, then try to delete the last tag of _blueEditingTagControl.tags, it will crash). So I suggest to use _defauldEditingTagControl.tags = [tags mutableCopy] instead of _defauldEditingTagControl.tags = tags directly, it may fix all crashes in Sample.

btw _defauldEditingTagControl -> _defaultEditingTagControl  another spelling mistake :P

**Comment by AntonKuznetsov** [comment]
Hello again @xnth97,
Sorry for such a late reply. I was busy at work lately.
I've merged your pull request.
Thank you for your contribution, I really appreciate that.

**Comment by ali312** [comment]
Hello again @xnth97,
Sorry for such a late reply. I was busy at work lately.
I've merged your pull request.
Thank you for your contribution, I really appreciate that.
