### ISSUE TITLE
Add cocoapod spec, pls?

### ISSUE THREAD

**Issue by appfabtech** [ali312/TLTagsControl#8]

**Comment by mohlman3** [comment]
Submitted a PR for this.  Until it gets merged, you can point your podfile to my forked copy that has the podpsec, like this:

```
pod 'TLTagsControl', :git => 'https://github.com/mohlman3/TLTagsControl.git'
```

**Comment by AntonKuznetsov** [comment]
Hello @pcecchetti 
Thanks to @mohlman3 you can now use 
pod 'TLTagsControl', :git => 'https://github.com/ali312/TLTagsControl.git'
